sensio_framework_extra:
    router:
        annotations: false
    request:
        converters: true
        auto_convert: true
        disable: ['doctrine.orm']
    view:
        annotations: false
    cache:
        annotations: false
    security:
        annotations: false
        expression_language: sensio_framework_extra.security.expression_language.default
